### PR TITLE
Removed toLowerCase() on key names in API

### PR DESCRIPTION
**Pull request by Scoutski**
Just wanted to allow the theme to support camelCase for API properties. Unless there is a reason I'm unaware of that it's forcing property names to lower case?

### CODE REVIEW

**Review by handrews — APPROVED** [review]
Seems reasonable to me.
@tajo is this related to the id/ID workaround or does that take place elsewhere?

**Comment by tajo** [comment]
@handrews probably, let me double check ... definitely it's there for some reason :)

**Comment by Scoutski** [comment]
Hey guys, sorry to be a bother, any updates on this? We're just telling people to change it manually for now.

**Comment by davidbanham** [comment]
Thanks for the merge! Any idea when we should expect an npm release with this included?

**Comment by dogmatic69** [comment]
Just come across this issue, any plans to push a release to npm?

**Comment by handrews** [comment]
@tajo @toekneestuck what's the release policy for this?  Seems like it should have been published a while back.

**Pull request merged**
