### PR TITLE
Seperates multiple types with comma space

### PR DESCRIPTION
**Pull request by Relequestual**
Fixes https://github.com/cloudflare/doca/issues/31

### CODE REVIEW

**Comment by tajo** [comment]
Thanks. Can you please fix this (`npm run lint`):

```bash
~/Projects/doca-bootstrap-theme: Relequestual-patch-1 npm run lint

> doca-bootstrap-theme@0.2.0 lint /Users/miksu/Projects/doca-bootstrap-theme
> eslint components || true


/Users/miksu/Projects/doca-bootstrap-theme/components/objectDefinitionTable.js
  32:1  error  Line 32 exceeds the maximum line length of 100  max-len

✖ 1 problem (1 error, 0 warnings)
```

**Comment by tajo** [comment]
(I should set up travis to run npm run lint on PRs.)

**Comment by Relequestual** [comment]
Done! =]

I MAY make a few more pull requests. Finally got this thing working! =D

**Comment by tajo** [comment]
```bash
~/Projects/doca-bootstrap-theme: Relequestual-patch-1 npm run lint

> doca-bootstrap-theme@0.2.0 lint /Users/miksu/Projects/doca-bootstrap-theme
> eslint components || true


/Users/miksu/Projects/doca-bootstrap-theme/components/objectDefinitionTable.js
  32:68  error  Trailing spaces not allowed  no-trailing-spaces
  33:65  error  Trailing spaces not allowed  no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)

~/Projects/doca-bootstrap-theme: Relequestual-patch-1 
```

**Comment by tajo** [comment]
Also, in case that master was updated and there are merge conflicts, we prefer rebase over merge (it keeps the history clean and PR diff shows only your changes). But that's ok.

**Comment by Relequestual** [comment]
Sure. I was trying to do it directly through github rather than checking it out. In future I'll rebase =]

**Comment by Relequestual** [comment]
I can see the trailing spaces, and am about to push a change which removes them, however running `npm run lint` doesn't pick the issue up for me. I would guess you have some sort of global lint guide, which has elements you haven't included in this projects lint file.

**Comment by tajo** [comment]
Thanks. 

> I would guess you have some sort of global lint guide

I don't. We are using airbnb's config and it includes the `no-trailing-spaces` [rule resulting to error](https://github.com/airbnb/javascript/blob/b6fc6dc7c3cb76497db0bb81edaa54d8f3427796/packages/eslint-config-airbnb-base/rules/style.js#L275).

**Comment by handrews** [comment]
> We are using airbnb's config and it includes the no-trailing-spaces rule resulting to error.

We should be including whatever lint config we are using in the project as published to GitHub.

**Comment by tajo** [comment]
We do [that](https://github.com/cloudflare/doca-bootstrap-theme/blob/master/.eslintrc#L3).

**Comment by handrews** [comment]
@tajo cool I misinterpreted your response

**Comment by Relequestual** [comment]
Right, I noticed that, which is why it's weird it didn't pick up. Oh well.

**Pull request merged**
