### PR TITLE
Theme redesign

### PR DESCRIPTION
**Pull request by tajo**
So, I'm working on https://github.com/cloudflare/doca/issues/8 which means changing the design of sidebar but then I went a bit deeper and basically overhauled the whole bootstrap theme since it looked pretty bad (when I first published that I didn't spend any time with styling).

**I am not a designer by any means** but this new theme should improve:
- [vertical rhythm](https://zellwk.com/blog/why-vertical-rhythms/), baseline is 25px, it should be more pleasant for eyes
- less borders, cleaner look
- less crazy colors so it looks more professional
- the left sidebar is automatically hidden at certain window width (better for responsiveness) 

## New

screen shot 2017-01-31 at 5 35 14 pm

## Old

screen shot 2017-01-31 at 5 44 27 pm

Thoughts?

### CODE REVIEW

**Comment by handrews** [comment]
@tajo screenshot looks great to me, I'll review the code tomorrow.

**Comment by Relequestual** [comment]
This is really nice!

Today I was thinking... I wonder if I could make a [slate](https://github.com/lord/slate) based theme. Something I may look into.

**Comment by tajo** [comment]
Even if there is some space for improvements, I would like to see this merged without more changes (if we can agree that it's an improvement over the current design) since https://github.com/cloudflare/doca-bootstrap-theme/pull/4 needs these commits to be reviewable and working. We can address further improvements later in separate issue.

**Comment by handrews** [comment]
@tajo yeah I suspect that will be fine, just got caught up in a bunch of stuff today and had to leave early.  Will finish this off tomorrow, ping me if I haven't by mid-afternoon.

**Review by handrews — APPROVED** [review]

**Pull request merged**
